
# List of property test files that target removed V2 orchestration modules
collect_ignore = [
    "test_api_client_property_tests.py",
    "test_api_key_manager_property_tests.py",
    "test_api_model_management_data_models_property_tests.py",
    "test_cache_manager_property_tests.py",
    "test_cli_interface_property_tests.py",
    "test_concurrency_property_tests.py",
    "test_config_manager_property_tests.py",
    "test_cost_tracker_property_tests.py",
    "test_error_handler_property_tests.py",
    "test_evaluator_property_tests.py",
    "test_failover_manager_property_tests.py",
    "test_graceful_degradation_property_tests.py",
    "test_health_checker_property_tests.py",
    "test_main_agent_property_tests.py",
    "test_metrics_exporter_property_tests.py",
    "test_model_optimizer_property_tests.py",
    "test_orchestration_property_tests.py",
    "test_performance_monitor_property_tests.py",
    "test_provider_adapters_property_tests.py",
    "test_rate_limiter_property_tests.py",
    "test_registry_property_tests.py",
    "test_selector_property_tests.py",
    "test_workflow_engine_property_tests.py",
    "test_cross_referencing_property_tests.py",
    "test_directory_structure_mirroring.py",
    "test_health_check_completeness.py",
]
