"""Artifact Manager - Structured artifact storage and retrieval.

Manages all artifacts generated by agents: prompts, requests, responses,
documents, reports, and code. Enforces naming conventions and provides
retrieval by type, date, task, or sprint.
"""

import json
import shutil
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

from .logging import get_logger

logger = get_logger(__name__)


class ArtifactType:
    """Artifact type constants."""
    PROMPT = "prompts"
    REQUEST = "requests"
    RESPONSE = "responses"
    DOCUMENT = "docs"
    REPORT = "reports"
    CODE = "code"
    SKILL = "skills"
    WORKFLOW = "workflows"
    CONFIG = "config"


@dataclass
class Artifact:
    """An artifact generated by an agent.

    Attributes:
        id: Unique artifact identifier.
        type: Artifact type (from ArtifactType constants).
        name: Artifact name/title.
        content: Artifact content (text).
        metadata: Additional metadata.
        created_at: Creation timestamp.
        source_agent: Agent that created this artifact.
        task_id: Related task ID.
    """
    id: str
    type: str
    name: str
    content: str = ""
    metadata: Dict[str, Any] = field(default_factory=dict)
    created_at: str = field(default_factory=lambda: datetime.now().isoformat())
    source_agent: str = ""
    task_id: str = ""


class ArtifactManager:
    """Manages structured artifact storage and retrieval.

    Directory structure:
        .agentic_sdlc/artifacts/
        ├── prompts/       # Generated prompts
        ├── requests/      # User request logs
        ├── responses/     # Agent response logs
        ├── docs/          # Generated documentation
        ├── reports/       # Self-improvement reports
        ├── code/          # Generated code
        ├── skills/        # Generated skills
        └── workflows/     # Generated workflows

    Example:
        >>> manager = ArtifactManager(base_dir=Path(".agentic_sdlc/artifacts"))
        >>> artifact = manager.store(
        ...     type=ArtifactType.PROMPT,
        ...     name="login-prompt-v1",
        ...     content="...",
        ... )
        >>> retrieved = manager.get(artifact.id)
    """

    def __init__(self, base_dir: Path):
        """Initialize the artifact manager.

        Args:
            base_dir: Base directory for artifact storage.
        """
        self._base_dir = base_dir
        self._ensure_dirs()
        self._index: Dict[str, Artifact] = {}
        self._load_index()

    def store(
        self,
        type: str,
        name: str,
        content: str,
        metadata: Optional[Dict[str, Any]] = None,
        source_agent: str = "",
        task_id: str = "",
    ) -> Artifact:
        """Store a new artifact.

        Args:
            type: Artifact type (use ArtifactType constants).
            name: Artifact name.
            content: Content to store.
            metadata: Optional metadata.
            source_agent: Agent that created the artifact.
            task_id: Related task ID.

        Returns:
            Created Artifact.
        """
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        artifact_id = f"{type}_{name}_{timestamp}"

        artifact = Artifact(
            id=artifact_id,
            type=type,
            name=name,
            content=content,
            metadata=metadata or {},
            source_agent=source_agent,
            task_id=task_id,
        )

        # Write content
        type_dir = self._base_dir / type
        type_dir.mkdir(parents=True, exist_ok=True)
        content_file = type_dir / f"{name}_{timestamp}.md"
        content_file.write_text(content, encoding="utf-8")

        # Update index
        self._index[artifact_id] = artifact
        self._save_index()

        logger.info(f"Stored artifact: {artifact_id}")
        return artifact

    def get(self, artifact_id: str) -> Optional[Artifact]:
        """Retrieve an artifact by ID.

        Args:
            artifact_id: Artifact identifier.

        Returns:
            Artifact if found, None otherwise.
        """
        return self._index.get(artifact_id)

    def list_by_type(self, type: str) -> List[Artifact]:
        """List artifacts by type.

        Args:
            type: Artifact type.

        Returns:
            List of artifacts of the given type.
        """
        return [a for a in self._index.values() if a.type == type]

    def list_by_task(self, task_id: str) -> List[Artifact]:
        """List artifacts by task ID.

        Args:
            task_id: Task identifier.

        Returns:
            List of artifacts related to the task.
        """
        return [a for a in self._index.values() if a.task_id == task_id]

    def search(self, query: str) -> List[Artifact]:
        """Search artifacts by name or content keywords.

        Args:
            query: Search query.

        Returns:
            List of matching artifacts.
        """
        query_lower = query.lower()
        results = []
        for artifact in self._index.values():
            if (
                query_lower in artifact.name.lower()
                or query_lower in artifact.content.lower()[:500]
            ):
                results.append(artifact)
        return results

    def delete(self, artifact_id: str) -> bool:
        """Delete an artifact.

        Args:
            artifact_id: Artifact ID.

        Returns:
            True if deleted, False if not found.
        """
        if artifact_id not in self._index:
            return False

        del self._index[artifact_id]
        self._save_index()
        return True

    @property
    def count(self) -> int:
        """Total number of artifacts."""
        return len(self._index)

    def _ensure_dirs(self) -> None:
        """Create directory structure."""
        for artifact_type in [
            ArtifactType.PROMPT, ArtifactType.REQUEST, ArtifactType.RESPONSE,
            ArtifactType.DOCUMENT, ArtifactType.REPORT, ArtifactType.CODE,
            ArtifactType.SKILL, ArtifactType.WORKFLOW, ArtifactType.CONFIG,
        ]:
            (self._base_dir / artifact_type).mkdir(parents=True, exist_ok=True)

    def _load_index(self) -> None:
        """Load artifact index from disk."""
        index_file = self._base_dir / "index.json"
        if index_file.exists():
            try:
                with open(index_file) as f:
                    data = json.load(f)
                self._index = {
                    k: Artifact(**v) for k, v in data.items()
                }
            except Exception:
                self._index = {}

    def _save_index(self) -> None:
        """Save artifact index to disk."""
        index_file = self._base_dir / "index.json"
        try:
            data = {
                k: {
                    "id": v.id, "type": v.type, "name": v.name,
                    "content": v.content[:500],  # Truncate for index
                    "metadata": v.metadata, "created_at": v.created_at,
                    "source_agent": v.source_agent, "task_id": v.task_id,
                }
                for k, v in self._index.items()
            }
            with open(index_file, "w") as f:
                json.dump(data, f, indent=2)
        except Exception as e:
            logger.error(f"Failed to save artifact index: {e}")
